# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

#networks:
#  shared-network:
#    driver: bridge

services:
  # This is the core CRUD based service.
  sugar-api:
    container_name: sugar-api
#    networks:
#      - shared-network
    image: igorgomonov/sugar-api-amd64:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    environment:
      - SUGAR_DB_HOST=db
      - SUGAR_DB_DISABLE_TLS=1 # This is only disabled for our development enviroment.
      # - GODEBUG=gctrace=1
