apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sugar-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      name: sugar-api
      labels:
        service: sugar-api
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:2.11
          ports:
            - name: zipkin
              containerPort: 9411
          resources: {}
        - name: sugar-api
          image: gcr.io/{{PROJECT}}/sugar-api-amd64:1.0
          env:
            - name: SUGAR_DB_HOST
              value: {{PRIVATE_DB_IP}}
          ports:
            - name: sugar-api
              containerPort: 3000
            - name: debug
              containerPort: 4000
          resources: {}
        - name: metrics
          image: gcr.io/{{PROJECT}}/metrics-amd64:1.0
          env:
            - name: METRICS_COLLECT_FROM
              value: "http://localhost:4000/debug/vars"
          ports:
            - name: metrics
              containerPort: 3001
            - name: debug
              containerPort: 4001
          resources: {}
status: {}
