apiVersion: v1
kind: Service
metadata:
  name: sugar-api
spec:
  selector:
    service: sugar-api
  ports:
    - name: "zipkin"
      port: 9411
      targetPort: 9411
    - name: "sugar-api"
      port: 3000
      targetPort: 3000
    - name: "sugar-api-debug"
      port: 4000
      targetPort: 4000
    - name: "metrics"
      port: 3001
      targetPort: 3001
    - name: "metrics-debug"
      port: 4001
      targetPort: 4001
status:
  loadBalancer: {}